// Roblox-RS Code Generator
// Generates Luau code from our AST representation

use crate::transpiler::ast::*;
use std::fmt::Write;

/// Generate Luau code from a Program AST node
pub fn generate_luau(program: &Program) -> Result<String, String> {
    let mut output = String::new();
    
    // Add RobloxRS runtime header
    writeln!(output, "-- Generated by Roblox-RS Transpiler v1.0").map_err(|e| e.to_string())?;
    writeln!(output, "-- Do not manually edit this file").map_err(|e| e.to_string())?;
    writeln!(output).map_err(|e| e.to_string())?;
    
    // Generate code for each node in the program
    for node in &program.body {
        generate_node(&mut output, node, 0)?;
        writeln!(output).map_err(|e| e.to_string())?;
    }
    
    Ok(output)
}

/// Generate code for a single AST node with proper indentation
fn generate_node(output: &mut String, node: &LuauNode, indent_level: usize) -> Result<(), String> {
    let indent = "    ".repeat(indent_level);
    
    match node {
        LuauNode::Program(program) => {
            for node in &program.body {
                generate_node(output, node, indent_level)?;
                writeln!(output).map_err(|e| e.to_string())?;
            }
        }
        
        LuauNode::Function(function) => {
            // Function declaration
            if function.is_local {
                write!(output, "{}local ", indent).map_err(|e| e.to_string())?;
            }
            
            if function.is_method {
                write!(output, "{}function {}(", indent, function.name).map_err(|e| e.to_string())?;
            } else {
                write!(output, "{}function {}(", indent, function.name).map_err(|e| e.to_string())?;
            }
            
            // Function parameters
            for (i, param) in function.params.iter().enumerate() {
                if i > 0 {
                    write!(output, ", ").map_err(|e| e.to_string())?;
                }
                write!(output, "{}", param.name).map_err(|e| e.to_string())?;
                
                // Add parameter type annotation (Luau supports type annotations)
                if let Some(param_type) = &param.param_type {
                    write!(output, ": {}", param_type).map_err(|e| e.to_string())?;
                }
            }
            
            // Close function signature
            writeln!(output, ")").map_err(|e| e.to_string())?;
            
            // Function body
            for statement in &function.body.statements {
                generate_node(output, statement, indent_level + 1)?;
            }
            
            // End function
            writeln!(output, "{}end", indent).map_err(|e| e.to_string())?;
        }
        
        LuauNode::Variable(variable) => {
            // Variable declaration
            if variable.is_local {
                write!(output, "{}local ", indent).map_err(|e| e.to_string())?;
            }
            
            write!(output, "{}", variable.name).map_err(|e| e.to_string())?;
            
            // Variable type annotation
            if let Some(var_type) = &variable.var_type {
                write!(output, ": {}", var_type).map_err(|e| e.to_string())?;
            }
            
            // Variable initialization
            if let Some(initializer) = &variable.initializer {
                write!(output, " = ").map_err(|e| e.to_string())?;
                generate_expression(output, initializer)?;
            }
            
            writeln!(output).map_err(|e| e.to_string())?;
        }
        
        LuauNode::Class(class) => {
            // Class is represented as a table in Luau
            writeln!(output, "{}local {} = {{}}", indent, class.name).map_err(|e| e.to_string())?;
            
            // If there's a parent class, set up inheritance
            if let Some(parent) = &class.parent {
                writeln!(output, "{}setmetatable({}, {{__index = {}}})", indent, class.name, parent).map_err(|e| e.to_string())?;
            }
            
            // Properties
            for property in &class.properties {
                write!(output, "{}{}.{}", indent, class.name, property.name).map_err(|e| e.to_string())?;
                
                if let Some(initializer) = &property.initializer {
                    write!(output, " = ").map_err(|e| e.to_string())?;
                    generate_expression(output, initializer)?;
                    writeln!(output).map_err(|e| e.to_string())?;
                } else {
                    writeln!(output, " = nil").map_err(|e| e.to_string())?;
                }
            }
            
            // Methods
            for method in &class.methods {
                write!(output, "{}function {}.{}(", indent, class.name, method.name).map_err(|e| e.to_string())?;
                
                // Add 'self' as first parameter for methods
                let mut first_param = true;
                if method.is_method {
                    write!(output, "self").map_err(|e| e.to_string())?;
                    first_param = false;
                }
                
                // Method parameters
                for param in &method.params {
                    if !first_param {
                        write!(output, ", ").map_err(|e| e.to_string())?;
                    }
                    first_param = false;
                    write!(output, "{}", param.name).map_err(|e| e.to_string())?;
                }
                
                writeln!(output, ")").map_err(|e| e.to_string())?;
                
                // Method body
                for statement in &method.body.statements {
                    generate_node(output, statement, indent_level + 1)?;
                }
                
                writeln!(output, "{}end", indent).map_err(|e| e.to_string())?;
            }
            
            // Constructor function
            writeln!(output, "{}function {}.new(...)", indent, class.name).map_err(|e| e.to_string())?;
            writeln!(output, "{}    local self = setmetatable({{}}, {{__index = {}}})", indent, class.name).map_err(|e| e.to_string())?;
            writeln!(output, "{}    {}.__init(self, ...)", indent, class.name).map_err(|e| e.to_string())?;
            writeln!(output, "{}    return self", indent).map_err(|e| e.to_string())?;
            writeln!(output, "{}end", indent).map_err(|e| e.to_string())?;
        }
        
        LuauNode::Module(module) => {
            // Module is represented as a table in Luau
            writeln!(output, "{}local {} = {{}}", indent, module.name).map_err(|e| e.to_string())?;
            
            // Module body
            for node in &module.body {
                generate_node(output, node, indent_level + 1)?;
            }
            
            // Export the module
            writeln!(output, "{}return {}", indent, module.name).map_err(|e| e.to_string())?;
        }
        
        LuauNode::Expression(expression) => {
            write!(output, "{}", indent).map_err(|e| e.to_string())?;
            generate_expression(output, expression)?;
            writeln!(output).map_err(|e| e.to_string())?;
        }
        
        LuauNode::Statement(statement) => {
            match statement {
                Statement::ExpressionStatement(expression) => {
                    write!(output, "{}", indent).map_err(|e| e.to_string())?;
                    generate_expression(output, expression)?;
                    writeln!(output).map_err(|e| e.to_string())?;
                }
                
                Statement::ReturnStatement(expression) => {
                    write!(output, "{}return ", indent).map_err(|e| e.to_string())?;
                    if let Some(expr) = expression {
                        generate_expression(output, expr)?;
                    }
                    writeln!(output).map_err(|e| e.to_string())?;
                }
                
                Statement::BreakStatement => {
                    writeln!(output, "{}break", indent).map_err(|e| e.to_string())?;
                }
                
                Statement::ContinueStatement => {
                    writeln!(output, "{}continue", indent).map_err(|e| e.to_string())?;
                }
                
                Statement::AssignmentStatement { left, right } => {
                    write!(output, "{}", indent).map_err(|e| e.to_string())?;
                    generate_expression(output, left)?;
                    write!(output, " = ").map_err(|e| e.to_string())?;
                    generate_expression(output, right)?;
                    writeln!(output).map_err(|e| e.to_string())?;
                }
            }
        }
        
        LuauNode::Block(block) => {
            for statement in &block.statements {
                generate_node(output, statement, indent_level)?;
            }
        }
        
        LuauNode::IfStatement(if_statement) => {
            write!(output, "{}if ", indent).map_err(|e| e.to_string())?;
            generate_expression(output, &if_statement.test)?;
            writeln!(output, " then").map_err(|e| e.to_string())?;
            
            // Consequent (if body)
            for statement in &if_statement.consequent.statements {
                generate_node(output, statement, indent_level + 1)?;
            }
            
            // Alternate (else body)
            if let Some(alternate) = &if_statement.alternate {
                writeln!(output, "{}else", indent).map_err(|e| e.to_string())?;
                for statement in &alternate.statements {
                    generate_node(output, statement, indent_level + 1)?;
                }
            }
            
            writeln!(output, "{}end", indent).map_err(|e| e.to_string())?;
        }
        
        LuauNode::ForLoop(for_loop) => {
            // For loops in Luau are a bit different from Rust
            // We'll implement a numeric for loop for simplicity
            
            // Initialize variable
            if let Some(initializer) = &for_loop.initializer {
                generate_node(output, &*initializer, indent_level)?;
            }
            
            // Condition-based loop (while loop)
            if let Some(test) = &for_loop.test {
                write!(output, "{}while ", indent).map_err(|e| e.to_string())?;
                generate_expression(output, test)?;
                writeln!(output, " do").map_err(|e| e.to_string())?;
                
                // Loop body
                for statement in &for_loop.body.statements {
                    generate_node(output, statement, indent_level + 1)?;
                }
                
                // Update expression
                if let Some(update) = &for_loop.update {
                    write!(output, "{}    ", indent).map_err(|e| e.to_string())?;
                    generate_expression(output, update)?;
                    writeln!(output).map_err(|e| e.to_string())?;
                }
                
                writeln!(output, "{}end", indent).map_err(|e| e.to_string())?;
            }
        }
        
        LuauNode::WhileLoop(while_loop) => {
            write!(output, "{}while ", indent).map_err(|e| e.to_string())?;
            generate_expression(output, &while_loop.test)?;
            writeln!(output, " do").map_err(|e| e.to_string())?;
            
            // Loop body
            for statement in &while_loop.body.statements {
                generate_node(output, statement, indent_level + 1)?;
            }
            
            writeln!(output, "{}end", indent).map_err(|e| e.to_string())?;
        }
        
        LuauNode::Comment(comment) => {
            writeln!(output, "{}-- {}", indent, comment).map_err(|e| e.to_string())?;
        }
    }
    
    Ok(())
}

/// Generate code for an expression
fn generate_expression(output: &mut String, expression: &Expression) -> Result<(), String> {
    match expression {
        Expression::Identifier(name) => {
            write!(output, "{}", name).map_err(|e| e.to_string())?;
        }
        
        Expression::Literal(literal) => {
            match literal {
                Literal::String(value) => {
                    write!(output, "\"{}\"", value.replace("\"", "\\\"")).map_err(|e| e.to_string())?;
                }
                Literal::Number(value) => {
                    write!(output, "{}", value).map_err(|e| e.to_string())?;
                }
                Literal::Boolean(value) => {
                    write!(output, "{}", value).map_err(|e| e.to_string())?;
                }
                Literal::Nil => {
                    write!(output, "nil").map_err(|e| e.to_string())?;
                }
            }
        }
        
        Expression::BinaryExpression { left, operator, right } => {
            write!(output, "(").map_err(|e| e.to_string())?;
            generate_expression(output, left)?;
            
            match operator {
                BinaryOperator::Add => write!(output, " + ").map_err(|e| e.to_string())?,
                BinaryOperator::Subtract => write!(output, " - ").map_err(|e| e.to_string())?,
                BinaryOperator::Multiply => write!(output, " * ").map_err(|e| e.to_string())?,
                BinaryOperator::Divide => write!(output, " / ").map_err(|e| e.to_string())?,
                BinaryOperator::Modulo => write!(output, " % ").map_err(|e| e.to_string())?,
                BinaryOperator::Exponent => write!(output, " ^ ").map_err(|e| e.to_string())?,
                BinaryOperator::Concatenate => write!(output, " .. ").map_err(|e| e.to_string())?,
                BinaryOperator::Equal => write!(output, " == ").map_err(|e| e.to_string())?,
                BinaryOperator::NotEqual => write!(output, " ~= ").map_err(|e| e.to_string())?,
                BinaryOperator::LessThan => write!(output, " < ").map_err(|e| e.to_string())?,
                BinaryOperator::LessThanOrEqual => write!(output, " <= ").map_err(|e| e.to_string())?,
                BinaryOperator::GreaterThan => write!(output, " > ").map_err(|e| e.to_string())?,
                BinaryOperator::GreaterThanOrEqual => write!(output, " >= ").map_err(|e| e.to_string())?,
                BinaryOperator::And => write!(output, " and ").map_err(|e| e.to_string())?,
                BinaryOperator::Or => write!(output, " or ").map_err(|e| e.to_string())?,
            }
            
            generate_expression(output, right)?;
            write!(output, ")").map_err(|e| e.to_string())?;
        }
        
        Expression::UnaryExpression { operator, argument } => {
            match operator {
                UnaryOperator::Minus => write!(output, "-").map_err(|e| e.to_string())?,
                UnaryOperator::Not => write!(output, "not ").map_err(|e| e.to_string())?,
                UnaryOperator::Length => write!(output, "#").map_err(|e| e.to_string())?,
            }
            
            generate_expression(output, argument)?;
        }
        
        Expression::FunctionCall { callee, arguments } => {
            generate_expression(output, callee)?;
            write!(output, "(").map_err(|e| e.to_string())?;
            
            for (i, arg) in arguments.iter().enumerate() {
                if i > 0 {
                    write!(output, ", ").map_err(|e| e.to_string())?;
                }
                generate_expression(output, arg)?;
            }
            
            write!(output, ")").map_err(|e| e.to_string())?;
        }
        
        Expression::MemberExpression { object, property, computed } => {
            generate_expression(output, object)?;
            
            if *computed {
                write!(output, "[").map_err(|e| e.to_string())?;
                generate_expression(output, property)?;
                write!(output, "]").map_err(|e| e.to_string())?;
            } else {
                if let Expression::Identifier(name) = &**property {
                    write!(output, ".{}", name).map_err(|e| e.to_string())?;
                } else {
                    // Fallback to computed property access if not an identifier
                    write!(output, "[").map_err(|e| e.to_string())?;
                    generate_expression(output, property)?;
                    write!(output, "]").map_err(|e| e.to_string())?;
                }
            }
        }
        
        Expression::TableExpression { properties } => {
            write!(output, "{{").map_err(|e| e.to_string())?;
            
            for (i, (key, value)) in properties.iter().enumerate() {
                if i > 0 {
                    write!(output, ", ").map_err(|e| e.to_string())?;
                }
                
                // Handle different key types
                if let Expression::Identifier(name) = key {
                    write!(output, "{} = ", name).map_err(|e| e.to_string())?;
                } else {
                    write!(output, "[").map_err(|e| e.to_string())?;
                    generate_expression(output, key)?;
                    write!(output, "] = ").map_err(|e| e.to_string())?;
                }
                
                generate_expression(output, value)?;
            }
            
            write!(output, "}}").map_err(|e| e.to_string())?;
        }
        
        Expression::ArrayExpression { elements } => {
            write!(output, "{{").map_err(|e| e.to_string())?;
            
            for (i, element) in elements.iter().enumerate() {
                if i > 0 {
                    write!(output, ", ").map_err(|e| e.to_string())?;
                }
                generate_expression(output, element)?;
            }
            
            write!(output, "}}").map_err(|e| e.to_string())?;
        }
    }
    
    Ok(())
}
