#[cfg(test)]
mod rojo_standalone_tests {
    use std::fs;
    use std::path::{Path, PathBuf};
    use crate::rojo::RojoManager;
    
    // Create a temporary directory for testing
    fn setup_test_dir() -> PathBuf {
        let temp_dir = std::env::temp_dir().join("roblox_rs_test_dir");
        if !temp_dir.exists() {
            fs::create_dir_all(&temp_dir).unwrap();
        }
        temp_dir
    }
    
    #[test]
    fn test_rojo_project_creation() {
        let test_dir = setup_test_dir();
        let project_path = test_dir.join("default.project.json");
        
        // Clean up any existing project file
        if project_path.exists() {
            fs::remove_file(&project_path).unwrap();
        }
        
        // Create a new Rojo manager and create a default project
        let mut rojo_manager = RojoManager::new(&project_path);
        let result = rojo_manager.create_default_project("test-project", &test_dir.join("src"));
        
        assert!(result.is_ok(), "Failed to create project: {:?}", result.err());
        assert!(project_path.exists(), "Project file was not created");
        
        // Check that the project file contains the expected content
        let content = fs::read_to_string(&project_path).unwrap();
        assert!(content.contains("test-project"), "Project name not found in project file");
        assert!(content.contains("ServerScriptService"), "ServerScriptService not found in project file");
        assert!(content.contains("ReplicatedStorage"), "ReplicatedStorage not found in project file");
    }
    
    #[test]
    fn test_compile_with_rojo_direct() {
        let test_dir = setup_test_dir();
        let project_path = test_dir.join("test_game.project.json");
        let src_dir = test_dir.join("src");
        
        // Clean up any existing project file
        if project_path.exists() {
            fs::remove_file(&project_path).unwrap();
        }
        
        // Ensure source directory exists
        if !src_dir.exists() {
            fs::create_dir_all(&src_dir).unwrap();
        }
        
        // Create a new Rojo manager and create a default project
        let mut rojo_manager = RojoManager::new(&project_path);
        rojo_manager.create_default_project("test-game", &src_dir).unwrap();
        
        // Create a simple Lua file that would be the output of compilation
        let lua_code = "-- Generated by roblox-rs\nlocal function greet(name) return \"Hello, \"..name..\"!\" end\nreturn greet";
        let lua_file = src_dir.join("main.lua");
        fs::write(&lua_file, lua_code).unwrap();
        
        // Load the project and verify mapping
        let result = rojo_manager.load_project();
        assert!(result.is_ok(), "Failed to load project: {:?}", result.err());
        
        // Verify the project file was created
        assert!(project_path.exists(), "Project file was not created");
        
        // Verify the Lua file exists
        assert!(lua_file.exists(), "Lua file was not created");
    }
}
