#[cfg(test)]
mod type_declaration_tests {
    use std::path::Path;
    use crate::{compile_with_options, CompileOptions, OptimizationLevel};
    use crate::types::declarations::TypeDeclarationManager;
    
    #[test]
    fn test_type_declaration_manager() {
        // Create a type declaration manager
        let mut manager = TypeDeclarationManager::new();
        
        // Load declarations from our example files
        let type_dir = Path::new("/Users/dunno/Documents/projects/roblox-rs/roblox-rs-core/src/types/declarations");
        let result = manager.load_declarations_from_directory(type_dir);
        
        // Ensure loading was successful
        assert!(result.is_ok(), "Failed to load type declarations: {:?}", result.err());
        
        // Generate type definitions
        let luau_types = manager.generate_luau_types();
        
        // Check that key types were generated
        assert!(luau_types.contains("Vector3"), "Vector3 type not found in generated types");
        assert!(luau_types.contains("RobloxRS"), "RobloxRS runtime namespace not found in generated types");
        assert!(luau_types.contains("Color3"), "Color3 type not found in generated types");
        
        // Print the first few lines for inspection
        let preview: String = luau_types.lines().take(20).collect::<Vec<&str>>().join("\n");
        println!("Generated Luau Type Definitions (first 20 lines):\n{}", preview);
    }
    
    #[test]
    fn test_compile_with_type_declarations() {
        // Simple Rust function
        let rust_code = r#"
            fn add(a: i32, b: i32) -> i32 {
                a + b
            }
        "#;
        
        // Compile with type declarations
        let result = compile_with_options(rust_code, CompileOptions {
            include_runtime: true,
            debug_mode: false,
            enable_parallelization: false,
            optimization_level: OptimizationLevel::Default,
            generate_type_declarations: true,
            type_declarations_dir: Some("/Users/dunno/Documents/projects/roblox-rs/roblox-rs-core/src/types/declarations".to_string()),
            rojo_project_path: None,
            serve_with_rojo: false,
            open_rojo_browser: false,
        });
        
        assert!(result.is_ok(), "Compilation failed: {:?}", result.err());
        let luau_code = result.unwrap();
        
        // Check that type declarations are included
        assert!(luau_code.contains("--[[Generated by Roblox-RS Type Declaration System]]"), 
                "Type declaration header not found in output");
        assert!(luau_code.contains("Vector3"), "Vector3 type not found in output");
        assert!(luau_code.contains("RobloxRS"), "RobloxRS namespace not found in output");
        
        // Print the first 40 lines for inspection
        let preview: String = luau_code.lines().take(40).collect::<Vec<&str>>().join("\n");
        println!("Generated Luau Code with Type Declarations (first 40 lines):\n{}", preview);
    }
    
    #[test]
    fn test_integration_with_runtime_and_type_declarations() {
        // Simple Rust function that will be both typechecked and use the runtime
        let rust_code = r#"
            /// Convert Rust tuple to Roblox Vector3
            fn create_vector3(x: f32, y: f32, z: f32) -> (f32, f32, f32) {
                (x, y, z)
            }
            
            /// Use the runtime helper to create a pool
            fn create_part_pool(size: i32) -> String {
                format!("Created pool of size {}", size)
            }
        "#;
        
        // Compile with all features enabled
        let result = compile_with_options(rust_code, CompileOptions {
            include_runtime: true,
            debug_mode: true,
            enable_parallelization: true,
            optimization_level: OptimizationLevel::Aggressive,
            generate_type_declarations: true,
            type_declarations_dir: Some("/Users/dunno/Documents/projects/roblox-rs/roblox-rs-core/src/types/declarations".to_string()),
            rojo_project_path: None,
            serve_with_rojo: false,
            open_rojo_browser: false,
        });
        
        assert!(result.is_ok(), "Compilation failed: {:?}", result.err());
        let luau_code = result.unwrap();
        
        // Verify type declarations are included
        assert!(luau_code.contains("--[[Generated by Roblox-RS Type Declaration System]]"), 
                "Type declaration header not found in output");
        
        // Verify runtime helpers are included
        assert!(luau_code.contains("RobloxRS ="), "Runtime helper not included");
        assert!(luau_code.contains("RobloxRS.Pool"), "Object pooling not included");
        
        // Verify debug symbols are included
        assert!(luau_code.contains("DEBUG_SYMBOLS"), "Debug symbols not included");
        
        // Verify parallel utilities are included
        assert!(luau_code.contains("RobloxRS.Parallel"), "Parallel execution utilities not included");
        
        // Verify tuple-to-Vector3 optimization (this might be dependent on the optimizer implementation)
        assert!(luau_code.contains("Vector3") || luau_code.contains("vector"), 
                "Vector3 conversion not found in output");
    }
}
