use std::fs;
use std::f64::consts::PI;
use std::path::Path;

mod pages;

const SSP: [u64; 15] = [2,3,5,7,11,13,17,19,23,29,31,41,47,59,71];
const C1: [i64; 15] = [4371,782,133,50,16,11,6,5,3,2,2,1,0,0,0];
const GENUS: [u8; 15] = [0,0,0,0,1,0,1,1,2,2,2,3,4,5,6];
const EXP: [u8; 15] = [46,20,9,6,2,3,1,1,1,1,1,1,1,1,1];
const ROLES: [&str; 15] = ["Earth","Earth","Earth","Earth","Earth","Earth",
    "Spoke","Hub","Hub","Heaven","Heaven","Heaven",
    "Invisible","Invisible","Invisible"];

fn clk(n: f64) -> f64 { (n * PI / 3.0).cos() }
fn rot(n: f64) -> f64 { -(n * PI / 3.0).cos() }
fn frm(n: i32) -> i32 { if n % 2 == 0 { 1 } else { -1 } }

fn css() -> &'static str { include_str!("style.css") }

fn nav(active: &str) -> String {
    let pages = [("index.html","Overview"),("gyroscope.html","Gyroscope"),
        ("analysis.html","Analysis"),("walk.html","Walk"),
        ("chain.html","Chain"),("code.html","Code")];
    let mut s = String::from("<nav>");
    for (href, label) in &pages {
        let cls = if *href == active { " class=\"active\"" } else { "" };
        s += &format!("<a href=\"{}\"{}>{}</a>", href, cls, label);
    }
    s += "</nav>";
    s
}

fn head(title: &str) -> String {
    format!("<!DOCTYPE html>\n<html><head><meta charset=\"utf-8\">\
<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\
<title>{} · Monster Gyroscope</title>\n<style>{}</style></head><body>", title, css())
}

fn foot() -> &'static str {
    "<div class=\"footer\">Monster Gyroscope · Cl(15,0,0) · 47×59×71=196883 · O⁶=I · Generated by CI</div>\n</body></html>"
}

fn role_tag(role: &str) -> String {
    let cls = match role {
        "Earth" => "earth", "Hub" => "hub", "Spoke" => "spoke",
        "Heaven" => "heaven", "Invisible" => "inv", _ => "earth"
    };
    format!("<span class=\"tag tag-{}\">{}</span>", cls, role)
}

fn escape(s: &str) -> String {
    s.replace('&',"&amp;").replace('<',"&lt;").replace('>',"&gt;")
}

fn main() {
    let out = Path::new("output/site");
    fs::create_dir_all(out).unwrap();

    let pages: Vec<(&str, String)> = vec![
        ("index.html", pages::index()),
        ("gyroscope.html", pages::gyroscope()),
        ("analysis.html", pages::analysis()),
        ("walk.html", pages::walk()),
        ("chain.html", pages::chain()),
        ("code.html", pages::code()),
    ];

    for (name, html) in &pages {
        fs::write(out.join(name), html).unwrap();
        println!("  wrote {}: {} bytes", name, html.len());
    }
    println!("Static site generated in output/site/ ({} pages)", pages.len());
}
